### ISSUE TITLE
Error while patching : java.io.IOException: This archive contains unclosed entries.

### ISSUE THREAD

**Issue by sridharamirneni** [sassoftware/loguccino#14]
?? Patching /opt/sas/sashome/SASEnvironmentManager/2.5/installs/hypericsvr_lax_2.5_M3_HFE8M004/SASHome/xx/SASEnvironmentManager/2.5/server-5.8.0.tar.gz::server-5.8.0-EE/hqapi1-client-6.0.2/lib/log4j-core-2.11.1.jar
? null
? null
? null
? null
? null
? null
? null
? null
? null
? null
ERROR: Error while patching : java.io.IOException: This archive contains unclosed entries.
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:291)
        at com.sas.vulnerabilities.utils.ArchiveCompressUtils.compressArchive(ArchiveCompressUtils.java:108)
        at com.sas.vulnerabilities.patcher.SequentialPatcher.packageNextArchive(SequentialPatcher.java:38)
        at com.sas.vulnerabilities.patcher.SequentialPatcher.packageNextArchive(SequentialPatcher.java:41)
        at com.sas.vulnerabilities.patcher.SequentialPatcher.patchSingleCVE(SequentialPatcher.java:58)
        at com.sas.vulnerabilities.patcher.SequentialPatcherInventoryTask.runSingleCveInventoryPath(SequentialPatcherInventoryTask.java:68)
        at com.sas.vulnerabilities.patcher.SequentialPatcherInventoryTask.run(SequentialPatcherInventoryTask.java:93)
        at lukfor.progress.tasks.Task.call(Task.java:39)
        at lukfor.progress.tasks.Task.call(Task.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

**Comment by sridharamirneni** [comment]
@boemska-nik is there any update?

**Comment by boemska-nik** [comment]
What OS / version is this with, and what was the full command line you ran & with what user?

**Comment by boemska-nik** [comment]
Hi @sridharamirneni,

Coming back to this. We weren't able to replicate this issue, but it _could_ be resolved by the 3.2.0 release because of the changes that were made to the repacker. Are you able to test this release and let us know if you still face this issue?
